### ISSUE TITLE
"loaded" signal not firing

### ISSUE THREAD

**Issue by oneirophon** [hugemenace/resonate#16] opened 2024-02-26 21:12 UTC
I'm running Resonate 2.3.4 under Godot 4.2.1, and I'm trying to create a script that will start music regardless of which is loaded first, my BGM script or the MusicManager.

Here's the script:

```
extends Node

var initial_track: String
var music_manager_loaded: bool = false

@onready var timer = $Timer

func ready():
	if Events.connect("music_changed", Callable(self, "_on_music_changed")) != 0:
		Errors.event_not_found()
	if MusicManager.connect("loaded", Callable(self, "_on_MusicManager_loaded")) != 0:
		Errors.event_not_found()

func play_bgm(track):
	initial_track = track
	if music_manager_loaded == true:
		MusicManager.play("bgm", track)

func _on_music_changed(track):
	MusicManager.play("bgm", track)

	
func _on_MusicManager_loaded():
	print("MusicManager loaded")
	music_manager_loaded = true
	if initial_track != null:
		MusicManager.play("bgm", initial_track)
	else:
		timer.start()
		
		
func _on_Timer_timeout():
	if initial_track != null:
		MusicManager.play("bgm", initial_track)
		queue_free()
	else:
		timer.start()
```

I've verified that the MusicManager is loading and that the arguments I'm feeding to `MusicManager.play()` are correct by setting the timer to autostart, which plays the music just fine, but I can't get the `_on_MusicManager_loaded` function to trigger.

**Comment by tristan-hm** [comment] 2024-02-26 23:46
The first question is, how are you currently loading this script? Is it attached to a node present in the scene tree when the game first loads, or is it later added in at runtime?

The thing to keep in mind is that both the Sound and Music manager's `loaded` signals only fire once. So, if your script is added in at some point after that event has been emitted, you've missed it, and it will never fire again.

There are a couple of other events you can hook into for the music manager: `updated` and `banks_updated`. However, the circumstances under which those events are emitted may mean your music doesn't start playing automatically either. You can, however, guarantee that  `updated` and `banks_updated` will fire if the scene associated with your script has a MusicBank.

Context aside, one tactic you could use to ensure your current implementation works is to do a check on the MusicManager's `has_loaded` property, e.g.:

```GDScript
func ready():
	if Events.connect("music_changed", Callable(self, "_on_music_changed")) != 0:
		Errors.event_not_found()
	
	if MusicManager.has_loaded:
		# Start playing music as the manager has already loaded.
		MusicManager.play("bgm", initial_track)
	else:
		# Wait until the loaded event has been fired, as the manager is still being prepared.
		if MusicManager.connect("loaded", Callable(self, "_on_MusicManager_loaded")) != 0:
			Errors.event_not_found()
```

**Comment by oneirophon** [comment] 2024-02-27 00:09
The script is attached to a node in the scene tree when the game loads up. As for the fact that the signal is only emitted once, the thing is, before I added the code that used that signal, I was getting an error when calling `MusicManager.play()` that said the Music Manager wasn't ready, and to use the `loaded` signal to fix the issue, so it doesn't seem like the problem should be that the signal fired before the script was loaded.

All that said, the `has_loaded` property sounds perfect for what I'm trying to do!

**Comment by tristan-hm** [comment] 2024-02-27 05:58
There's always the possibility of an edge case needing to be handled here, so it's worth investigating further. Before you added the `loaded` signal connection code, were you calling `MusicManager.play(...)` from the same spot (your `ready` function) when you got the Resonate warning?

Also, `ready` isn't the standard Godot lifecycle method, but `_ready` is, so I assume you're calling `ready` from somewhere else in your code?

**Comment by oneirophon** [comment] 2024-02-28 19:33
Oh, whoops! That would explain it. Looks like the signal wasn't being connected because I left out that underscore. I was calling `MusicManager.play()` from my `play_bgm()` function, which was called from another script, so that got called but my `ready()` function was never called.

**Comment by tristan-hm** [comment] 2024-02-29 01:59
Ah, well, it sounds like the problem is solved then! I'll close this issue.

**Closed by tristan-hm** 2024-02-29 01:59 UTC
Labels: question, topic: music
